/*
 * generated by Xtext 2.21.0
 */
package org.xtext.bb;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class BbDslStandaloneSetup extends BbDslStandaloneSetupGenerated {

	public static void doSetup() {
		new BbDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
