/*
 * generated by Xtext 2.21.0
 */
package org.xtext.dor.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.dor.ui.internal.DorActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DorDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(DorActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		DorActivator activator = DorActivator.getInstance();
		return activator != null ? activator.getInjector(DorActivator.ORG_XTEXT_DOR_DORDSL) : null;
	}

}
