/*
 * generated by Xtext 2.21.0
 */
package org.xtext.bb.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class BbDslUiModule extends AbstractBbDslUiModule {

	public BbDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
