/*
 * generated by Xtext 2.27.0
 */
package org.xtext.tcl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TclStandaloneSetup extends TclStandaloneSetupGenerated {

	public static void doSetup() {
		new TclStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
