/*
 * generated by Xtext 2.21.0
 */
package org.xtext.dvg.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.dvg.DvgDslRuntimeModule;
import org.xtext.dvg.DvgDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DvgDslIdeSetup extends DvgDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DvgDslRuntimeModule(), new DvgDslIdeModule()));
	}
	
}
