/*
 * generated by Xtext 2.21.0
 */
package org.xtext.dor.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class DorDslUiModule extends AbstractDorDslUiModule {

	public DorDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
