/*
 * generated by Xtext 2.21.0
 */
package org.xtext.dvg.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class DvgDslUiModule extends AbstractDvgDslUiModule {

	public DvgDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
