/*
 * generated by Xtext 2.21.0
 */
package org.xtext.dor.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.dor.DorDslRuntimeModule;
import org.xtext.dor.DorDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DorDslIdeSetup extends DorDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DorDslRuntimeModule(), new DorDslIdeModule()));
	}
	
}
