/*
 * generated by Xtext 2.27.0
 */
package org.xtext.tcl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.tcl.TclRuntimeModule;
import org.xtext.tcl.TclStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class TclIdeSetup extends TclStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new TclRuntimeModule(), new TclIdeModule()));
	}
	
}
