/*
 * generated by Xtext 2.21.0
 */
package org.xtext.bb.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.bb.BbDslRuntimeModule;
import org.xtext.bb.BbDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class BbDslIdeSetup extends BbDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new BbDslRuntimeModule(), new BbDslIdeModule()));
	}
	
}
