package org.xtext.bb.generator;

import org.eclipse.xtend2.lib.StringConcatenation;

@SuppressWarnings("all")
public class Node {
  public static CharSequence generateNodeClassCode() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("class Node<T> {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private String name;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private List<SimpleEntry<List<List<SimpleEntry<String,Integer>>>,T>> vsp;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private List<SimpleEntry<List<List<SimpleEntry<String,Integer>>>,List<T>>> vsp_2;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public Node(String name) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("this.name = name;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public Node(String name, List<SimpleEntry<List<List<SimpleEntry<String,Integer>>>,T>> vsp) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("this.name = name;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("this.vsp = vsp;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public String name() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return this.name;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("List<SimpleEntry<List<List<SimpleEntry<String,Integer>>>,T>> vsp() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return this.vsp;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("List<SimpleEntry<List<List<SimpleEntry<String,Integer>>>,List<T>>> vsp_2() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return this.vsp_2;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("T vsp(int slotIndex) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return this.vsp.get(slotIndex).getValue();");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("List<T> vsp_2(int slotIndex) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return this.vsp_2.get(slotIndex).getValue();");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("SimpleEntry<List<List<SimpleEntry<String,Integer>>>,T> slot(int slotIndex) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return this.vsp.get(slotIndex);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("SimpleEntry<List<List<SimpleEntry<String,Integer>>>,List<T>> slot_2(int slotIndex) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return this.vsp_2.get(slotIndex);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("List<List<SimpleEntry<String,Integer>>> header(int slotIndex) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("if (this instanceof NodeObjectList) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("return this.vsp_2.get(slotIndex).getKey();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("else {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("return this.vsp.get(slotIndex).getKey();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public List<List<SimpleEntry<String,Integer>>> initUniqueResourceIdHeader(int id) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("List<List<SimpleEntry<String,Integer>>> header = new ArrayList<List<SimpleEntry<String,Integer>>>();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("List<SimpleEntry<String,Integer>> headerRow = new ArrayList<SimpleEntry<String,Integer>>();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("SimpleEntry<String,Integer> pair = new SimpleEntry<String,Integer>(\"UNIQUE_RESOURCE_ID\", id);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("headerRow.add(pair);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("header.add(headerRow);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return header;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void initLeaf(List<T> leafValues) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("this.vsp = new ArrayList<SimpleEntry<List<List<SimpleEntry<String,Integer>>>,T>>();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("for (int i = 0; i < leafValues.size(); i++) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("this.vsp.add(new SimpleEntry<List<List<SimpleEntry<String,Integer>>>,T>(null,leafValues.get(i)));");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void initLeaf_2(List<List<T>> leafValues) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("this.vsp_2 = new ArrayList<SimpleEntry<List<List<SimpleEntry<String,Integer>>>,List<T>>>();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("for (int i = 0; i < leafValues.size(); i++) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("this.vsp_2.add(new SimpleEntry<List<List<SimpleEntry<String,Integer>>>,List<T>>(null,leafValues.get(i)));");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void initLeaf(List<T> leafValues, int id) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("this.vsp = new ArrayList<SimpleEntry<List<List<SimpleEntry<String,Integer>>>,T>>();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("for (int i = 0; i < leafValues.size(); i++) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("this.vsp.add(new SimpleEntry<List<List<SimpleEntry<String,Integer>>>,T>(initUniqueResourceIdHeader(id),leafValues.get(i)));");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void initLeaf_2(List<List<T>> leafValues, int id) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("this.vsp_2 = new ArrayList<SimpleEntry<List<List<SimpleEntry<String,Integer>>>,List<T>>>();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("for (int i = 0; i < leafValues.size(); i++) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("this.vsp_2.add(new SimpleEntry<List<List<SimpleEntry<String,Integer>>>,List<T>>(initUniqueResourceIdHeader(id),leafValues.get(i)));");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}\t\t\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void assignVSP_2(List<SimpleEntry<List<List<SimpleEntry<String,Integer>>>,List<T>>> p) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("this.vsp_2 = p;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}\t\t\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("List <T> values() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("List<T> tmp = new ArrayList<T>();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("for (int i = 0; i < this.vsp.size(); i++) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("tmp.add(this.vsp.get(i).getValue());");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("return tmp;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }

  public static CharSequence generateNodeObjectClassCode() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("class NodeObject extends Node<Object> {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public NodeObject(String name) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("super(name);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public NodeObject(String name, List<SimpleEntry<List<List<SimpleEntry<String,Integer>>>,Object>> vsp) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("super(name,vsp);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }

  public static String generateNodeObjectListClassCode() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("class NodeObjectList extends Node<Object> {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public NodeObjectList(String name) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("super(name);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public NodeObjectList(String name, List<SimpleEntry<List<List<SimpleEntry<String,Integer>>>,Object>> vsp) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("super(name,vsp);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }

  public static CharSequence generateNodePsClassCode() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("class NodePs extends Node<Map<String,Double>> {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public NodePs(String name) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("super(name);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public NodePs(String name, List<SimpleEntry<List<List<SimpleEntry<String,Integer>>>,Map<String,Double>>> vsp) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("super(name,vsp);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
}
