/**
 * generated by Xtext 2.21.0
 */
package org.xtext.bb.generator;

import java.util.Map;

@SuppressWarnings("all")
public class VariabilityInformation {
  public int numberAllocations;

  public Map<String, Integer> active;

  public Map<String, Integer> passive;
}
