/*
 * generated by Xtext 2.27.0
 */
package org.xtext.tcl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TclUiModule extends AbstractTclUiModule {

	public TclUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
